CREATE TABLE IF NOT EXISTS users (
    email    VARCHAR(50)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    created  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS weather (
    id      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    city    VARCHAR(50)     NOT NULL,
    min_t   DECIMAL(4,1)    NOT NULL,
    max_t   DECIMAL(4,1)    NOT NULL,
    period  ENUM('AM','PM') NOT NULL,
    date    DATE            NOT NULL,
    created DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_city_period_date (city, period, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
